### ISSUE TITLE
`Client execute too frequently` error message after prolonged use

### ISSUE THREAD

**Issue by Ostromogilski** [DeyeCloudDevelopers/deye-openapi-client-sample-code#3]
Hi team,

I've been using the Deye API for about a month, polling the `https://eu1-developer.deyecloud.com/v1.0/device/latest` endpoint every 10 seconds. Initially, everything worked fine, but recently I started getting the following error response:

```json
{
  "code": "2101002",
  "success": false,
  "msg": "client execute Too Frequently",
  "requestId": "1a0f3163aeb39086"
}
```

I haven’t found any mention of rate limits or polling frequency restrictions in the Deye API documentation. Could you please clarify if there is a rate limit in place and what the expected polling interval should be?

**Comment by DeyeCloudDevelopers** [comment]
For most of devices upload latest data every 5 minutes, if your device upload data each 5 minutes.
I recommend that you invoke /device/latest at least each 1 minute. This time interval will meet your need and would not put much pressure on our server.
